name: Dependabot Auto-merge

on:
  workflow_run:
    types:
      - completed
    workflows:
      # List all required workflow names here.
      - Build

permissions:
  contents: write
  pull-requests: read

jobs:
  auto_merge:
    name: Auto-merge
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.actor == 'dependabot[bot]'

    steps:
      - uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
